[package]
name = "chip8_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chip8_core = {path = "./chip8_core"}
bevy = "0.8.1"
bevy_egui = "0.16.1"